import os


SERVICE_NAME = "strategy-engine"
PORT = int(os.getenv("PORT", "8080"))

FEATURE_FACTORY_BASE_URL = os.getenv("FEATURE_FACTORY_BASE_URL", "http://feature-factory:8080")
STRICT_SCORE_THRESHOLD = float(os.getenv("STRICT_SCORE_THRESHOLD", "68"))

TRADE_SCORE_THRESHOLD = float(os.getenv("TRADE_SCORE_THRESHOLD", "68"))
OBSERVE_SCORE_THRESHOLD = float(os.getenv("OBSERVE_SCORE_THRESHOLD", "55"))

MACRO_NEUTRAL_PENALTY = float(os.getenv("MACRO_NEUTRAL_PENALTY", "8"))
MACRO_TRANSITION_PENALTY = float(os.getenv("MACRO_TRANSITION_PENALTY", "15"))

REGIME_TRANSITION_CAP = float(os.getenv("REGIME_TRANSITION_CAP", "72"))
REGIME_CHOP_CAP = float(os.getenv("REGIME_CHOP_CAP", "62"))
REGIME_RANGE_TREND_CAP = float(os.getenv("REGIME_RANGE_TREND_CAP", "58"))
REGIME_TREND_MEAN_REVERSION_CAP = float(os.getenv("REGIME_TREND_MEAN_REVERSION_CAP", "52"))
